import sys
import os
from bs4 import BeautifulSoup
import openpyxl as oxl
import re
from openpyxl import Workbook
from openpyxl.styles import Alignment, PatternFill, Font, Border, Side
from openpyxl.utils import get_column_letter
import tkinter as tk
from tkinter import Tk
from tkinter import messagebox as msg
import shutil
import datetime


html_content = """
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=11"/>
<meta name="generator" content="Doxygen 1.10.0"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>valve: C:/Users/노아_김원태/Desktop/workspace/docs/doc_냉매모듈드라이버/src/240111_src/app/ExValve_AppDiagState.c File Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<script type="text/javascript" src="clipboard.js"></script>
<script type="text/javascript" src="cookie.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr id="projectrow">
  <td id="projectalign">
   <div id="projectname">valve
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.10.0 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:d3d9a9a6595521f9666a5e94cc830dab83b65699&amp;dn=expat.txt MIT */
var searchBox = new SearchBox("searchBox", "search/",'.html');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:d3d9a9a6595521f9666a5e94cc830dab83b65699&amp;dn=expat.txt MIT */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(function() { init_search(); });
});
/* @license-end */
</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<div id="MSearchResults">
<div class="SRPage">
<div id="SRIndex">
<div id="SRResults"></div>
<div class="SRStatus" id="Loading">Loading...</div>
<div class="SRStatus" id="Searching">Searching...</div>
<div class="SRStatus" id="NoMatches">No Matches</div>
</div>
</div>
</div>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_d522931ffa1371640980b621734a4381.html">Users</a></li><li class="navelem"><a class="el" href="dir_0e38de9ace691dbfacb02c25b5d9139d.html">노아_김원태</a></li><li class="navelem"><a class="el" href="dir_689347de781a2edf8dac1816d997d5c7.html">Desktop</a></li><li class="navelem"><a class="el" href="dir_4ba65f40164eefad56f3e6d03877fd49.html">workspace</a></li><li class="navelem"><a class="el" href="dir_4a0c10672b191f2e30037760b2f8c4dc.html">docs</a></li><li class="navelem"><a class="el" href="dir_4c318ae887ba96279d18bfc47de6ab48.html">doc_냉매모듈드라이버</a></li><li class="navelem"><a class="el" href="dir_3e726e105ee0e82a8b7a307a96d5ffac.html">src</a></li><li class="navelem"><a class="el" href="dir_992f4c82b5c72c5d1943e7ddfd7d6583.html">240111_src</a></li><li class="navelem"><a class="el" href="dir_b95e0e0daeea68e9165c06a18dd38b68.html">app</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#func-members">Functions</a> &#124;
<a href="#var-members">Variables</a>  </div>
  <div class="headertitle"><div class="title">ExValve_AppDiagState.c File Reference</div></div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &quot;r_smc_entry.h&quot;</code><br />
<code>#include &quot;<a class="el" href="_ex_valve___app_diag_state_8h_source.html">ExValve_AppDiagState.h</a>&quot;</code><br />
</div><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a id="func-members" name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:a882533bc5a9b303149ea51da7451a57e" id="r_a882533bc5a9b303149ea51da7451a57e"><td class="memItemLeft" align="right" valign="top">static void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="#a882533bc5a9b303149ea51da7451a57e">appDiagUnderVoltageDebounceCheck</a> (void)</td></tr>
<tr class="separator:a882533bc5a9b303149ea51da7451a57e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3b2adb14830a5a1114ad12d45d1ede46" id="r_a3b2adb14830a5a1114ad12d45d1ede46"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="#a3b2adb14830a5a1114ad12d45d1ede46">ExValve_AppDiagDebounceInit</a> (void)</td></tr>
<tr class="separator:a3b2adb14830a5a1114ad12d45d1ede46"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0b2a1b8766e158420690eea0bf77084b" id="r_a0b2a1b8766e158420690eea0bf77084b"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="#a0b2a1b8766e158420690eea0bf77084b">AppDiagMcuUnderVoltageCheck</a> (void)</td></tr>
<tr class="separator:a0b2a1b8766e158420690eea0bf77084b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a09632891b58456b0388185c3c73f5afd" id="r_a09632891b58456b0388185c3c73f5afd"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="#a09632891b58456b0388185c3c73f5afd">AppDiagMcuOverVoltageCheck</a> (void)</td></tr>
<tr class="separator:a09632891b58456b0388185c3c73f5afd"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a529d16d39c2df048c755d086366c2587" id="r_a529d16d39c2df048c755d086366c2587"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="#a529d16d39c2df048c755d086366c2587">AppDiagMcuFaultCheck</a> (void)</td></tr>
<tr class="separator:a529d16d39c2df048c755d086366c2587"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae6daf6bff367b16790936085973e81b3" id="r_ae6daf6bff367b16790936085973e81b3"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="#ae6daf6bff367b16790936085973e81b3">AppDiagInternalErrorCheck</a> (void)</td></tr>
<tr class="separator:ae6daf6bff367b16790936085973e81b3"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac5712fa094c99a73b845800539df3de0" id="r_ac5712fa094c99a73b845800539df3de0"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="#ac5712fa094c99a73b845800539df3de0">AppDiagBatteryUnderVoltageCheck</a> (void)</td></tr>
<tr class="separator:ac5712fa094c99a73b845800539df3de0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0413f05f147116c87ea05511d1de43cc" id="r_a0413f05f147116c87ea05511d1de43cc"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="#a0413f05f147116c87ea05511d1de43cc">AppDiagBatteryOverVoltageCheck</a> (void)</td></tr>
<tr class="separator:a0413f05f147116c87ea05511d1de43cc"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ace5f5bf2a5735d05bd6d7926e27844b9" id="r_ace5f5bf2a5735d05bd6d7926e27844b9"><td class="memItemLeft" align="right" valign="top">int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="#ace5f5bf2a5735d05bd6d7926e27844b9">test</a> (int in1_int, double in2_double)</td></tr>
<tr class="separator:ace5f5bf2a5735d05bd6d7926e27844b9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5824e35e5edc6ac704ae4ebdd4a271d7" id="r_a5824e35e5edc6ac704ae4ebdd4a271d7"><td class="memItemLeft" align="right" valign="top">static void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="#a5824e35e5edc6ac704ae4ebdd4a271d7">AppDiagMcuDebounceCheck</a> (uint8_t diag_num)</td></tr>
<tr class="memdesc:a5824e35e5edc6ac704ae4ebdd4a271d7"><td class="mdescLeft">&#160;</td><td class="mdescRight">(brief)noah test description  <br /></td></tr>
<tr class="separator:a5824e35e5edc6ac704ae4ebdd4a271d7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afc013655e76b1f6c0240d297b2e49f28" id="r_afc013655e76b1f6c0240d297b2e49f28"><td class="memItemLeft" align="right" valign="top">static void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="#afc013655e76b1f6c0240d297b2e49f28">AppValveDebounceCheck</a> (uint8_t diag_num)</td></tr>
<tr class="separator:afc013655e76b1f6c0240d297b2e49f28"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aca5ae27204826c4a13b3df79e4a8b995" id="r_aca5ae27204826c4a13b3df79e4a8b995"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="#aca5ae27204826c4a13b3df79e4a8b995">ExValve_AppDiagCheck</a> (void)</td></tr>
<tr class="separator:aca5ae27204826c4a13b3df79e4a8b995"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acb917bff894d303fbc3ecd439442440a" id="r_acb917bff894d303fbc3ecd439442440a"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="#acb917bff894d303fbc3ecd439442440a">ExValve_AppDiagStateManager</a> (void)</td></tr>
<tr class="separator:acb917bff894d303fbc3ecd439442440a"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a id="var-members" name="var-members"></a>
Variables</h2></td></tr>
<tr class="memitem:a31c1327c2f831432906b9fe9b0aba748" id="r_a31c1327c2f831432906b9fe9b0aba748"><td class="memItemLeft" align="right" valign="top"><a class="el" href="structdiag__t.html">diag_t</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="#a31c1327c2f831432906b9fe9b0aba748">diag</a></td></tr>
<tr class="separator:a31c1327c2f831432906b9fe9b0aba748"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<h2 class="groupheader">Function Documentation</h2>
<a id="a0413f05f147116c87ea05511d1de43cc" name="a0413f05f147116c87ea05511d1de43cc"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a0413f05f147116c87ea05511d1de43cc">&#9670;&#160;</a></span>AppDiagBatteryOverVoltageCheck()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void AppDiagBatteryOverVoltageCheck </td>
          <td>(</td>
          <td class="paramtype">void</td>          <td class="paramname"><span class="paramname"></span></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="ac5712fa094c99a73b845800539df3de0" name="ac5712fa094c99a73b845800539df3de0"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ac5712fa094c99a73b845800539df3de0">&#9670;&#160;</a></span>AppDiagBatteryUnderVoltageCheck()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void AppDiagBatteryUnderVoltageCheck </td>
          <td>(</td>
          <td class="paramtype">void</td>          <td class="paramname"><span class="paramname"></span></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="ae6daf6bff367b16790936085973e81b3" name="ae6daf6bff367b16790936085973e81b3"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ae6daf6bff367b16790936085973e81b3">&#9670;&#160;</a></span>AppDiagInternalErrorCheck()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void AppDiagInternalErrorCheck </td>
          <td>(</td>
          <td class="paramtype">void</td>          <td class="paramname"><span class="paramname"></span></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a5824e35e5edc6ac704ae4ebdd4a271d7" name="a5824e35e5edc6ac704ae4ebdd4a271d7"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a5824e35e5edc6ac704ae4ebdd4a271d7">&#9670;&#160;</a></span>AppDiagMcuDebounceCheck()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">static void AppDiagMcuDebounceCheck </td>
          <td>(</td>
          <td class="paramtype">uint8_t</td>          <td class="paramname"><span class="paramname"><em>diag_num</em></span></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>(brief)noah test description </p>
<p>(detail)이 함수는 두 정수를 입력으로 받아서 그 합을 반환합니다. 예를 들어, add(3, 4)를 호출하면 7이 반환됩니다.</p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">diag_num</td><td>첫 번째 정수 </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>두 정수의 합</dd></dl>
<dl class="section note"><dt>Note</dt><dd>(note)이 함수는 더하기 연산을 수행합니다. </dd></dl>

</div>
</div>
<a id="a529d16d39c2df048c755d086366c2587" name="a529d16d39c2df048c755d086366c2587"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a529d16d39c2df048c755d086366c2587">&#9670;&#160;</a></span>AppDiagMcuFaultCheck()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void AppDiagMcuFaultCheck </td>
          <td>(</td>
          <td class="paramtype">void</td>          <td class="paramname"><span class="paramname"></span></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a09632891b58456b0388185c3c73f5afd" name="a09632891b58456b0388185c3c73f5afd"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a09632891b58456b0388185c3c73f5afd">&#9670;&#160;</a></span>AppDiagMcuOverVoltageCheck()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void AppDiagMcuOverVoltageCheck </td>
          <td>(</td>
          <td class="paramtype">void</td>          <td class="paramname"><span class="paramname"></span></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a0b2a1b8766e158420690eea0bf77084b" name="a0b2a1b8766e158420690eea0bf77084b"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a0b2a1b8766e158420690eea0bf77084b">&#9670;&#160;</a></span>AppDiagMcuUnderVoltageCheck()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void AppDiagMcuUnderVoltageCheck </td>
          <td>(</td>
          <td class="paramtype">void</td>          <td class="paramname"><span class="paramname"></span></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a882533bc5a9b303149ea51da7451a57e" name="a882533bc5a9b303149ea51da7451a57e"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a882533bc5a9b303149ea51da7451a57e">&#9670;&#160;</a></span>appDiagUnderVoltageDebounceCheck()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">static void appDiagUnderVoltageDebounceCheck </td>
          <td>(</td>
          <td class="paramtype">void</td>          <td class="paramname"><span class="paramname"></span></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="afc013655e76b1f6c0240d297b2e49f28" name="afc013655e76b1f6c0240d297b2e49f28"></a>
<h2 class="memtitle"><span class="permalink"><a href="#afc013655e76b1f6c0240d297b2e49f28">&#9670;&#160;</a></span>AppValveDebounceCheck()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">static void AppValveDebounceCheck </td>
          <td>(</td>
          <td class="paramtype">uint8_t</td>          <td class="paramname"><span class="paramname"><em>diag_num</em></span></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="aca5ae27204826c4a13b3df79e4a8b995" name="aca5ae27204826c4a13b3df79e4a8b995"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aca5ae27204826c4a13b3df79e4a8b995">&#9670;&#160;</a></span>ExValve_AppDiagCheck()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void ExValve_AppDiagCheck </td>
          <td>(</td>
          <td class="paramtype">void</td>          <td class="paramname"><span class="paramname"></span></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a3b2adb14830a5a1114ad12d45d1ede46" name="a3b2adb14830a5a1114ad12d45d1ede46"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a3b2adb14830a5a1114ad12d45d1ede46">&#9670;&#160;</a></span>ExValve_AppDiagDebounceInit()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void ExValve_AppDiagDebounceInit </td>
          <td>(</td>
          <td class="paramtype">void</td>          <td class="paramname"><span class="paramname"></span></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="acb917bff894d303fbc3ecd439442440a" name="acb917bff894d303fbc3ecd439442440a"></a>
<h2 class="memtitle"><span class="permalink"><a href="#acb917bff894d303fbc3ecd439442440a">&#9670;&#160;</a></span>ExValve_AppDiagStateManager()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void ExValve_AppDiagStateManager </td>
          <td>(</td>
          <td class="paramtype">void</td>          <td class="paramname"><span class="paramname"></span></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="ace5f5bf2a5735d05bd6d7926e27844b9" name="ace5f5bf2a5735d05bd6d7926e27844b9"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ace5f5bf2a5735d05bd6d7926e27844b9">&#9670;&#160;</a></span>test()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">int test </td>
          <td>(</td>
          <td class="paramtype">int</td>          <td class="paramname"><span class="paramname"><em>in1_int</em>, </span></td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">double</td>          <td class="paramname"><span class="paramname"><em>in2_double</em></span>&#160;)</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>(description)이 함수는 두 정수를 입력으로 받아서 그 합을 반환합니다. 예를 들어, add(3, 4)를 호출하면 7이 반환됩니다.</p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramdir">[in]</td><td class="paramname">in1_int</td><td>첫 번째 input </td></tr>
    <tr><td class="paramdir">[in]</td><td class="paramname">in2_double</td><td>두 번째 input </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>test return 0 </dd></dl>

</div>
</div>
<h2 class="groupheader">Variable Documentation</h2>
<a id="a31c1327c2f831432906b9fe9b0aba748" name="a31c1327c2f831432906b9fe9b0aba748"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a31c1327c2f831432906b9fe9b0aba748">&#9670;&#160;</a></span>diag</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="structdiag__t.html">diag_t</a> diag</td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
</div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated by&#160;<a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.10.0
</small></address>
</body>
</html>

"""
# BeautifulSoup을 사용하여 HTML 파싱
soup = BeautifulSoup(html_content, 'html.parser')

# 시작과 끝 태그를 찾습니다.
start_tag = soup.find('h2', class_='groupheader', string='Function Documentation')
end_tag = soup.find('h2', class_='groupheader', string='Variable Documentation')
medoclist = []

# 시작 태그와 끝 태그 사이의 div 태그를 찾습니다.
if start_tag and end_tag:
    div_items = start_tag.find_next_siblings('div', class_='memitem')

    # 각 div 태그에서 memdoc 클래스를 가진 div 태그를 찾아 출력합니다.
    for div_item in div_items:
        # memdoc 태그 찾기
        memdoc_div = div_item.find('div', class_='memdoc')

        # memdoc_div가 있고 내부에 내용이 있는지 확인
        if memdoc_div and memdoc_div.find_all():
            # description 추출
            description_tag = memdoc_div.find('p')
            description = description_tag.get_text(strip=True) if description_tag else ''

            # 파라미터 추출
            params_dl = memdoc_div.find('dl', class_='params')
            param_values = []
            if params_dl:
                for tr in params_dl.find_all('tr'):
                    params = [td.get_text(strip=True) if td.get_text(strip=True) else '파라미터 설명 없음' for td in tr.find_all('td') if not td.get('class')]
                    param_values.extend(params)

            # Return 값 추출
            return_dd_tag = memdoc_div.find('dl', class_='section return')
            return_dd = return_dd_tag.find('dd').get_text(strip=True) if return_dd_tag and return_dd_tag.find('dd') else ''

            result_list = [description, param_values, return_dd]
            medoclist.append(result_list)
        else:
            result_list = ['기능설명이 필요합니다', ['파라미터 설명이 필요합니다'], '리턴값 설명이 필요합니다.']
            medoclist.append(result_list)               

        # 만약에 'Variable Documentation'를 만나면 종료
        if div_item.find_previous('h2', class_='groupheader', string='Variable Documentation'):
            print("종료")
            break
else:
    print("시작 또는 끝 태그를 찾을 수 없습니다.")

# 결과 출력
print(medoclist.__len__())
print(medoclist)
for medoc in medoclist:
    print(medoc)

